import { createContext, useCallback, useContext, useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { FEATURED, OTHER_SENT, RESOLD_TODAY } from '../data/dispatch';
import { NOTIFICATIONS, TASKS } from '../data/feed';
import { NOW } from '../lib/format';

const KEY = 'valmo-save-lmdc-v1';

const initial = () => ({
  tasksDone: Object.fromEntries(TASKS.filter((t) => t.kind === 'done').map((t) => [t.id, true])),
  read: Object.fromEntries(NOTIFICATIONS.filter((n) => !n.unread).map((n) => [n.id, true])),
  dispatch: Object.fromEntries(FEATURED.map((f) => [f.id, f.initial])),
  extra: [], // notifications generated by actions in this session
  applied: false,
  returned: {},
  overrides: {},
  seq: 0,
});

function load() {
  try {
    const raw = localStorage.getItem(KEY);
    if (raw) return { ...initial(), ...JSON.parse(raw) };
  } catch { /* storage unavailable — start fresh */ }
  return initial();
}

const stamp = (s, n) => ({ id: 'x' + (s.seq + 1), time: NOW.time, ...n, fresh: true });

function reducer(s, a) {
  switch (a.type) {
    case 'toggleTask':
      return { ...s, tasksDone: { ...s.tasksDone, [a.id]: !s.tasksDone[a.id] } };
    case 'read':
      return { ...s, read: { ...s.read, [a.id]: true } };
    case 'readAll': {
      const all = {};
      [...NOTIFICATIONS, ...s.extra].forEach((n) => (all[n.id] = true));
      return { ...s, read: all };
    }
    case 'advance': {
      const f = FEATURED.find((x) => x.id === a.id);
      const cur = s.dispatch[a.id];
      const next = cur === 'pick' ? 'loading' : 'sent';
      if (cur === 'sent') return s;
      const dispatch = { ...s.dispatch, [a.id]: next };
      const text = next === 'loading'
        ? `${f.name.split(' · ')[0]} ${f.awb} picked from ${f.rack} and scanned at dock D-2 for ${f.shuttle}.`
        : `${f.name.split(' · ')[0]} ${f.awb} loaded on ${f.shuttle} for ${f.order} (${f.area}). Leaves ${f.departs} → Delhi South LMSC.`;
      const extra = [stamp(s, { kind: 'Dispatch', text, link: '/dispatch' }), ...s.extra];
      const allSent = Object.values(dispatch).every((v) => v === 'sent');
      const tasksDone = allSent ? { ...s.tasksDone, 't-dispatch': true } : s.tasksDone;
      return { ...s, dispatch, extra, tasksDone, seq: s.seq + 1 };
    }
    case 'applyAll':
      if (s.applied) return s;
      return { ...s, applied: true, seq: s.seq + 1, extra: [stamp(s, { kind: 'Retain', text: 'All 412 SKU recommendations applied: 214 units to rack R-4, 388 units to the RTO line-haul.', link: '/rto' }), ...s.extra] };
    case 'returnAll':
      return { ...s, returned: { ...s.returned, [a.id]: true }, seq: s.seq + 1, extra: [stamp(s, { kind: 'RTO', text: `All shelf units of ${a.name} (${a.id}) moved to the seller return bay.`, link: `/sku/${a.id}` }), ...s.extra] };
    case 'override':
      return { ...s, overrides: { ...s.overrides, [a.id]: a.days } };
    case 'reset':
      return initial();
    default:
      return s;
  }
}

const Ctx = createContext(null);

export function AppStateProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, undefined, load);
  const [toasts, setToasts] = useState([]);
  const tid = useRef(0);

  useEffect(() => {
    try { localStorage.setItem(KEY, JSON.stringify(state)); } catch { /* ignore */ }
  }, [state]);

  const toast = useCallback((msg) => {
    const id = ++tid.current;
    setToasts((t) => [...t, { id, msg }]);
    setTimeout(() => setToasts((t) => t.filter((x) => x.id !== id)), 3600);
  }, []);

  const derived = useMemo(() => {
    const notifications = [...state.extra, ...NOTIFICATIONS].map((n) => ({ ...n, unread: !state.read[n.id] }));
    const featuredSent = Object.values(state.dispatch).filter((v) => v === 'sent').length;
    const sent = OTHER_SENT + featuredSent;
    return {
      notifications,
      unread: notifications.filter((n) => n.unread).length,
      sent,
      due: RESOLD_TODAY - sent,
      tasksDoneCount: TASKS.filter((t) => state.tasksDone[t.id]).length,
    };
  }, [state]);

  const value = useMemo(() => ({ state, dispatch, toast, ...derived }), [state, derived, toast]);

  return (
    <Ctx.Provider value={value}>
      {children}
      <div className="toast-stack" role="status" aria-live="polite">
        {toasts.map((t) => (
          <div key={t.id} className="toast"><span>✓</span><span>{t.msg}</span></div>
        ))}
      </div>
    </Ctx.Provider>
  );
}

export const useApp = () => useContext(Ctx);
